# cspell:ignore q0rban tugboatqa updatedb
services:
  php:
    image: q0rban/tugboat-drupal:10
    default: true
    http: false
    depends: mysql
    commands:
      update: |
        set -eux

        # Check out a branch using the unique Tugboat ID for this repository, to
        # ensure we don't clobber an existing branch.
        git checkout -b $TUGBOAT_REPO_ID

        # Composer is hungry. You need a Tugboat project with a pretty sizeable
        # chunk of memory.
        export COMPOSER_MEMORY_LIMIT=-1

        # This is an environment variable we added in the Dockerfile that
        # provides the path to Drupal composer root (not the web root).
        cd $DRUPAL_COMPOSER_ROOT

        # We configure the Drupal project to use the checkout of the module as a
        # Composer package repository.
        composer config repositories.tugboat vcs $TUGBOAT_ROOT

        # Now we can require this module, specifying the branch name we created
        # above that uses the $TUGBOAT_REPO_ID environment variable.
        composer require drupal/scheduler:dev-$TUGBOAT_REPO_ID

        # Get other useful modules.
        composer require drupal/devel_generate drupal/module_filter drupal/admin_toolbar

        # Install Drupal on the site.
        vendor/bin/drush \
          --yes \
          --db-url=mysql://tugboat:tugboat@mysql:3306/tugboat \
          --site-name="Scheduler ${TUGBOAT_PREVIEW_NAME}" \
          --account-pass=admin \
          site:install standard

        # Show site status
        vendor/bin/drush status-report

        # Set up the files directory permissions.
        mkdir -p $DRUPAL_DOCROOT/sites/default/files
        chgrp -R www-data $DRUPAL_DOCROOT/sites/default/files
        chmod 2775 $DRUPAL_DOCROOT/sites/default/files
        chmod -R g+w $DRUPAL_DOCROOT/sites/default/files

        # Enable modules.
        vendor/bin/drush --yes pm:enable scheduler devel devel_generate module_filter admin_toolbar

        # Show versions.
        composer show drupal/scheduler | egrep 'name |vers'
        vendor/bin/drush pml | grep scheduler
        composer show drupal/devel | egrep 'name |vers'
        vendor/bin/drush pml | grep devel

        # Add some more items to the Devel toolbar. The default is 7 items, stored as 0 - 6, so new items start 7. These items
        # are already available in the devel toolbar 'config' but adding them here is equivalent to ticking the checkbox.
        vendor/bin/drush -y -q config-set devel.toolbar.settings toolbar_items.7 devel_generate.generate2
        vendor/bin/drush -y -q config-set devel.toolbar.settings toolbar_items.8 devel.configs_list
        vendor/bin/drush -y -q config-set devel.toolbar.settings toolbar_items.9 devel.switch_user
        vendor/bin/drush config-get devel.toolbar.settings

        # Scheduler general settings.
        vendor/bin/drush -y config-set scheduler.settings allow_date_only 1
        vendor/bin/drush -y config-set scheduler.settings default_time '22:06:00'
        vendor/bin/drush config-get scheduler.settings

        # Scheduler content settings.
        vendor/bin/drush -y config-set node.type.article third_party_settings.scheduler.publish_enable 1
        vendor/bin/drush -y config-set node.type.article third_party_settings.scheduler.unpublish_enable 1
        vendor/bin/drush -y config-set node.type.article third_party_settings.scheduler.expand_fieldset 'always'
        vendor/bin/drush -y config-set node.type.article third_party_settings.scheduler.fields_display_mode 'fieldset'
        vendor/bin/drush -y config-set node.type.article third_party_settings.scheduler.publish_past_date 'schedule'
        vendor/bin/drush config-get node.type.article third_party_settings

        # Create and update roles for scheduler permissions. We can re-use the pre-existing content_editor role.
        vendor/bin/drush role-add-perm 'content_editor' 'schedule publishing of nodes'
        vendor/bin/drush role-create 'content_viewer' 'Content viewer'
        vendor/bin/drush role-add-perm 'content_viewer' 'view scheduled content'

        # Add some permissions for all authenticated users.
        vendor/bin/drush role-add-perm 'authenticated' \
          "create article content, edit any article content, delete any article content, access content overview, \
           view own unpublished content, switch users, access toolbar, access administration pages, access devel information"

        # Create users and give them roles.
        vendor/bin/drush user-create 'Eddy editor'
        vendor/bin/drush user-add-role 'content_editor' 'Eddy editor'
        vendor/bin/drush user-create 'Vera viewer'
        vendor/bin/drush user-add-role 'content_viewer' 'Vera viewer'

        # Generate content.
        vendor/bin/drush devel-generate-content 3 --bundles=article --authors=1,2 --verbose
        vendor/bin/drush devel-generate-content 1 --bundles=page --authors=1,2 --verbose

        # @todo Add 'content overview' to tools menu.

      build: |
        set -eux

        # Delete and re-check out this branch in case this is built from a Base Preview.
        git branch -D $TUGBOAT_REPO_ID && git checkout -b $TUGBOAT_REPO_ID || true
        export COMPOSER_MEMORY_LIMIT=-1
        cd $DRUPAL_COMPOSER_ROOT
        composer install --optimize-autoloader

        # Update this module, including all dependencies.
        composer update drupal/scheduler --with-all-dependencies
        vendor/bin/drush --yes updatedb
        vendor/bin/drush cache:rebuild

  mysql:
    image: tugboatqa/mariadb
